### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by senthilnathan-dev** [libertarian-senthil/Matrix-calculator#2]
A new semantic error found in the module `mat_input.py`. if you give an inappropriate input such as __String__ as input it will print _"You've given a incorrect input"_ and again it continues the loop. Incase a user wants to quit the operation there's no way to end the loop. this issue needs to be corrected.
[mat_input.py](https://github.com/libertarian-senthil/Matrix-calculator/blob/main/matrix_project/matrix/mat_input.py)

**Comment by libertarian-senthil** [comment]
Error resolved reference [__mat_input.py__]()
